name: Docker

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        name: check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
            registry: 'docker.io'
            image: kdua1/new-github-app
            dockerfile: Dockerfile
            tags: v1, latest
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
                